// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1TST91KBBAocfzeHHhVLyXsHHx0XLbf8',
    appId: '1:390840313706:web:94618c1ed689a1a370e713',
    messagingSenderId: '390840313706',
    projectId: 'hwans-flutter-apps-1234',
    authDomain: 'hwans-flutter-apps-1234.firebaseapp.com',
    storageBucket: 'hwans-flutter-apps-1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWhMhUmfVUBa-_x3GS1uLull9ev4eM0g',
    appId: '1:390840313706:android:b2b5db7fd88c311e70e713',
    messagingSenderId: '390840313706',
    projectId: 'hwans-flutter-apps-1234',
    storageBucket: 'hwans-flutter-apps-1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBECq_JCQT8LfQWEpR52qiLMpE7GT7GyWc',
    appId: '1:390840313706:ios:cb123880dacf91e270e713',
    messagingSenderId: '390840313706',
    projectId: 'hwans-flutter-apps-1234',
    storageBucket: 'hwans-flutter-apps-1234.appspot.com',
    iosClientId: '390840313706-neokum6n8mun429onk491c5p96tgriop.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBECq_JCQT8LfQWEpR52qiLMpE7GT7GyWc',
    appId: '1:390840313706:ios:cb123880dacf91e270e713',
    messagingSenderId: '390840313706',
    projectId: 'hwans-flutter-apps-1234',
    storageBucket: 'hwans-flutter-apps-1234.appspot.com',
    iosClientId: '390840313706-neokum6n8mun429onk491c5p96tgriop.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );
}
